export { default as logoutLoader } from './logoutLoader.js';
export { default as loginLoader } from './loginLoader.js';
export { default as profileLoader } from './profileLoader.js'
export { default as companyLoader } from './companyLoader.js';
export { default as employeesLoader } from './employeesLoader.js';
export { default as departmentsLoader } from './departmentsLoader.js';
export { default as jobsLoader } from './jobsLoader.js';
export { default as addEmployeeLoader } from './addEmployeeLoader.js';
export { default as employeeLeavesLoader } from './employeeLeavesLoader.js';
export { default as leavesLoader } from './leavesLoader.js';
export { default as trainingsLoader } from './trainingsLoader.js';
export { default as addTraingLoader } from './addTrainingLoader.js';
export { default as evaluationLoader } from './evaluationLoader.js';
