export { default as SignUpForm } from './SignUpForm'
export { default as Register } from './Register'
export { default as Login } from './Login'
export { default as LandingPage } from './LandingPage'
export { default as Profile } from './Profile'
export { default as ErrorPage } from './ErrorPage'
export {default as CustomForm} from './CustomForm'
export { default as Home } from './Home'
